### ISSUE TITLE
I know the Dev suggested BeardedSpice as a replacement but after downloading that I can't use my media keys with Apple Music. (M1 Mac MINI w/ Big Sur) 

### ISSUE THREAD

**Issue by Airalyn** [milgra/macmediakeyforwarder#107]
Just a warning for anyone who tries the other suggested application! I couldn't get it to work and after uninstalling my keys didn't return back to their original functionality and I have no clue how to fix them.

**Comment by kalafalas** [comment]
Same thing happened to me. Running mac media key forwarder seems to be a work around, but I'm not sure how to do a proper fix without OS reinstall. You can also build the project in Xcode for a native version if you don't want to have to use Rosetta.

**Comment by robdekort** [comment]
Did anyone of you ever find a way to fix this?

**Comment by milgra** [comment]
Try this : https://github.com/quentinlesceller/macmediakeyforwarder/releases
