### ISSUE TITLE
M1/ASi/arm64 compatibility

### ISSUE THREAD

**Issue by kalafalas** [milgra/macmediakeyforwarder#108]
This is not really an issue, and I'm new to git hub so please let me know if there was a better place to put this.

I received an M1 MacBook Air and beardedspice did not functional at all on it. I went back to max media key forwarder, and to my surprise it worked perfectly.

I tried taking it a step further, and downloaded the Xcode project and re-compiled it with no changes at all in universal format, and it works brilliantly.

So for anyone with an M1, archive the project using your own free Apple ID and you can enjoy mac media key forwarder native, no Rosetta.

I know the dev has abandoned this project, but is there a way I can update the releases to include a native version?

Thank you!

**Comment by sh4d0wph03n1x** [comment]
Thank you for your work! You could always create your own repository, or you could fork this one.

**Comment by kalafalas** [comment]
Ok! I tied forking it and uploading my own release. This is my first time doing this! Please let me know if I did anything wrong, and if the app is singed properly/whatever :)
Thank you!

https://github.com/kalafalas/macmediakeyforwarder/releases/

**Comment by sh4d0wph03n1x** [comment]
Works fine for me. I'm just going to suggest an edit to the README if that's ok

**Comment by pclaisse** [comment]
Works like a charm :+1:

**Comment by ospfranco** [comment]
@kalafalas amazing thanks a lot!

**Comment by Soneji** [comment]
Hey @kalafalas , great work! Could you maybe contact @milgra about helping maintain the project? Then you could make it an official build and put it in this repo's releases?

**Comment by quentinlesceller** [comment]
Just to let you know that I forked MacMediaKeyForwarder, fixed the bug where the app freezes at launch and added universal binary. https://github.com/quentinlesceller/macmediakeyforwarder/releases/tag/v3.1.1
