### ISSUE TITLE
Have to restart the app on login for it to work with Spotify

### ISSUE THREAD

**Issue by mrjones2014** [milgra/macmediakeyforwarder#52]
When I log in, I have to restart this app before it will work with Spotify.

Mac OS High Sierra version 10.13.6
Spotify version: 1.0.86.337.ga8d5cef9
HighSierraMediaKeyEnabler version: 1.9 (build 5)

I have Spotify and HighSierraMediaKeyEnabler both set to start on login. But I have to restart HighSierraMediaKeyEnabler before it will work, at least with Spotify. I don't use iTunes so I can't speak to that.

**Comment by bpetrynski** [comment]
I have exactly the same problem.

**Comment by mrjones2014** [comment]
This app is nearly perfect, but for this one issue. If this were to be fixed I'd even donate to the developer because it saved me a lot of frustration.

**Comment by RonnieOnRails** [comment]
+1 here and was the same since on previous versions

**Comment by mrjones2014** [comment]
@milgra is this app still maintained? any news on this?

**Comment by milgra** [comment]
Thanks for the report, I will investigate

**Comment by milgra** [comment]
I can't reproduce the issue :( I close the lid of my MacBook often during the day and night but MMKF always works after wake.

**Comment by mrjones2014** [comment]
@milgra  what about after full system restart? I always shut down my MacBook.

**Comment by daquinoaldo** [comment]
> @milgra what about after full system restart? I always shut down my MacBook.

@mrjones2014 me too, but I don't have this problem. I use it a lot, I can try to reproduce the steps if you provide more information, I usually shut down the Mac twice a day.

**Comment by RonnieOnRails** [comment]
every time Mac goes on sleep, the app is unusable, I have to relaunch MMKF to get it work with Spotify

**Comment by daquinoaldo** [comment]
> every time Mac goes on sleep, the app is unusable, I have to relaunch MMKF to get it work with Spotify

Sorry, I can't help with that because I cannot put my Mac in sleep since it won't reconnect with mouse and keyboard when I wake it up and Apple says that they can't help me :(

**Comment by RonnieOnRails** [comment]
I didnt have the latest version, it seems that it fixed my issue <3

**Comment by milgra** [comment]
cool, thank you!

**Comment by RonnieOnRails** [comment]
19 days later… I had to relaunch the app twice for it to work. Better than before when I would do this every day… But still buggy somewhere ! Not a big deal though, but just so you know
