### ISSUE TITLE
sha256 sum of the release changed on your site

### ISSUE THREAD

**Issue by telyn** [milgra/macmediakeyforwarder#61]
Hiya,

I'm currently trying to update [the homebrew-cask](https://github.com/Homebrew/homebrew-cask/pull/54966) for MacMediaKeyEnabler. Quick disclaimer: I'm not affiliated with them in any way, just wanted to download it through `brew cask` and found I couldn't because of the broken URL, and thought I'd be helpful :smile:

The sha256 sum of [MacMediaKeyEnabler2.0.zip](
http://milgra.com/downloads/mmkf/MacMediaKeyForwarder2.0.zip) changed in the last few days, without altering the version number (probably when the URL was altered from hsme to mmkf.) Per [homebrew-cask's policy](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md) I've got to confirm that the sha256sum changing was deliberate on your part and not the result of some malicious actor updating your site for you, etc.

Could you confirm that a new build was released with the same version number? Just a comment on this issue or on the pull request confirming the new sha256sum would be great. Thanks :smile:

**Comment by milgra** [comment]
Hi, yes, I updated the zip/binary without incrementing the version :( Sorry about that, it won't happen any more if it breaks the cask. I'm also very grateful that you maintain MMKF-s cask repo, thank you! If you can put all cask-update related commands in a single shell file/script/etc, feel free to add it to the MMKF repository.

**Comment by telyn** [comment]
Aw, thanks for being so nice and helpful and commenting on the issue I linked to 😄 I don't know how to script forking homebrew and opening a pull request and I have lots of paid-for work to be getting back to but if I get time I'll have a think about it.

Cheers ^^
