### ISSUE TITLE
Missing the dot icon

### ISSUE THREAD

**Issue by tbnv** [milgra/macmediakeyforwarder#67]
Hello,

First and foremost, of course, this app is awesome.
Thank you.

I really **loved** the small, unobtrusive dot icon in the menu bar.
Is there a way or a trick to get it back?

If not, feature request: allow us to use the old dot icon. 😉

**Comment by daquinoaldo** [comment]
It is sufficient to replace the files icon* in the MacMediaKeyForwarder folder and rebuild the app.
However, it would be nice to have a setting to change between the two icons, the default one and the older one.

**Comment by milgra** [comment]
Hi, sorry but I changed the icon because it was a user request :) You can use an older version with the old icon or replace the icon file in the newer version of the app with the older icon file ( thats the simplest ).

**Comment by tbnv** [comment]
Hello. Ok, I see… however, the dot icon was a really cool trick to make the app unobtrusive in the menu bar, because it just looked like a separator. Anyway, I guess I'll replace it manually.

On a side note, what's the meaning of the new icon? I mean, I'm not sure I understand how the double arrow, that looks a bit like a select icon, is more relevant. 😀

**Comment by milgra** [comment]
Well, its a left/right arrow representing the prev/next functionality of the keyboard buttons :)

**Comment by Hum4n01d** [comment]
Looks more like a flipped Avicii logo 😂

**Comment by milgra** [comment]
I won't change it, but now you can CMD+drag the status bar item and drop it in the thrashbin if it disturbs you.
