### ISSUE TITLE
Run as background application

### ISSUE THREAD

**Issue by yochem** [milgra/macmediakeyforwarder#77]
Hey!

First of all, thank you for this app. It works really well and i really can't use the media keys on a mac without it anymore :smile:

Just one quick question, would it be possible to add the feature to run this application on the background? I like a clean menu bar and never change the settings of this app to be honest.

Thank you!

**Comment by mhugen** [comment]
+ 1. Id prefer to hide it from the menu bar and just open at login.

**Comment by DavidFafinski** [comment]
+1 a simple hide from the menu bar would be awesome, thanks for this app btw :)

**Comment by AdrnF** [comment]
+1 settings could be accessed with a preference panel

**Comment by yochem** [comment]
@milgra, is this something you would consider? Seems like there are more who think this is a great feature

**Comment by milgra** [comment]
From the latest version you can cmd+drag the status bar icon and drop it in the trash bin if you want to hide it but it will reappear after next startup, that's the closest I could get :)

**Comment by yochem** [comment]
Thanks, awesome! I know apps like [spectacle](https://github.com/eczarny/spectacle), that work like background applications, maybe you could find there how they did it. I'm sorry that I can't help you, I'm not familiar with OSX development
