### ISSUE TITLE
Use GitHub "Releases" feature (so that we can Watch them)

### ISSUE THREAD

**Issue by toblerpwn** [milgra/macmediakeyforwarder#79]
GitHub recently added the ability to "Watch" "Releases Only"

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1731512/55195936-3986d900-516b-11e9-9509-35ffee6080ae.png">

However, this is only useful if the repo uses Releases! I think for this sort of project, where there is no package manager or version control to pick up the latest automatically from a client (...or does it download the latest automatically?), this is a pretty good solution.

**Comment by hisaac** [comment]
I'll add my vote to this too. It would also be nice to have the binaries uploaded to the release so we can just download them directly from there.

**Comment by niij** [comment]
+1

**Comment by milgra** [comment]
Done! :)
