### ISSUE TITLE
Support VLC

### ISSUE THREAD

**Issue by LoganDark** [milgra/macmediakeyforwarder#80]
iTunes is shitty, sure, but I don't like Spotify because it bombards you with ads unless you pay them. I have some `mp3` files that I like to play with VLC, but when I tap the play button _before launching it_ it opens up iTunes until I focus VLC at least once. Using any of the iLife apps reverts this back to iTunes for some stupid reason, requiring me to switch back to VLC after using any of them like Keynote or Pages. Can this app be used to lock the keys to VLC instead of iTunes/Spotify?

**Comment by enomam** [comment]
Or any media app? I use Clementine myself. Media keys used to work, but now they don't.

**Comment by LoganDark** [comment]
Yeah, an app selector would be nice. I don't think you need special support when all apps should use the same hooks to support media keys. I'm not sure what Clementine is, but VLC shouldn't need to be explicitly supported either.

**Comment by enomam** [comment]
It's just another media player - i guess the closest thing to foobar on macos :)

**Comment by LoganDark** [comment]
I meant that as "I don't really care about the specifics, everything should work" rather than "please tell me about your niche music player". Never heard of foobar either. Sorry to disappoint.

**Comment by milgra** [comment]
Unfortunately no, VLC overrides MacMediaKeyForwarder's functionality, it catches events before MMKF :(

**Comment by LoganDark** [comment]
@milgra So what? MMKF can still forward events to VLC whenever VLC doesn't catch the events! What the hell!

**Comment by enomam** [comment]
> Unfortunately no, VLC overrides MacMediaKeyForwarder's functionality, it catches events before MMKF :(

What about forwarding keys to other apps in general? What if the issue were renamed to "Support other media players" ?

**Comment by LoganDark** [comment]
Come on, don't skip VLC like this, consider my proposal at least.

> So what? MMKF can still forward events to VLC whenever VLC doesn't catch the events...

**Comment by enomam** [comment]
I think the proposal makes perfect sense - MMKF literally just forwards the keys. It's up to the "recipient app" as to whether they act on it.

**Comment by LoganDark** [comment]
Yeah, @milgra apparently said that since VLC catches the keys first, MMKF can't act on it...? If VLC catches the keys, **MMKF's job is DONE and it _doesn't need to act on it_**. If VLC doesn't, MMKF gets it and MMKF can forward the keys to VLC.
