### ISSUE TITLE
Not working in 10.14.4

### ISSUE THREAD

**Issue by Crlax22** [milgra/macmediakeyforwarder#81]
Was working flawlessly for me until i updated to 10.14.4 and now reinstalling won't even work.

**Comment by GonMolon** [comment]
It works for me in 10.14.4 with a fresh install (I didn't have it installed before)

**Comment by andersonaguiar** [comment]
Not working for me with any version available.

**Comment by GonMolon** [comment]
Well it doesn't work only when I have Chrome focused. Otherwise it works like a charm. Is that expected behaviour or a bug? Am I the only one having it?

**Comment by scamper** [comment]
I can’t even install it. Not sure how to get around this after following those instructions to the letter. 
![Screen Shot 2019-04-30 at 12 45 42 PM](https://user-images.githubusercontent.com/370241/56988893-f773fd00-6b45-11e9-8333-c3d943d67131.png)

**Comment by scamper** [comment]
(HighSierraMediaKeyEnabler still works perfectly! Using that instead.)

**Comment by ajzeigert** [comment]
I have also noticed that I am getting the spinning beachball of death when attempting to run this app on 10.14.5.

**Comment by micnguyen** [comment]
Version 2.5 (build 2) works for me under OS X 10.14.4, with Chrome focused and unfocused

**Comment by GonMolon** [comment]
Okay, so it does work with Chrome focused after I manually restart the app. But after a while, it suddenly stops working again only when Chrome is focused. Restarting the app solves temporarily the problem. (Same behaviour with the latest version of HighSierraMediaKeyEnabler)

**Comment by Yokocapolo** [comment]
Not responding for me either on 10.14.5 using any version of Mac Media Key Forwarder. The latest version of High Sierra Media Key Forwarder works, so I'm using that for now. I tried to start the application with Chrome both open and closed, based on other comments, with no change. After about 10 seconds it becomes unresponsive in the Activity Monitor app.
After checking the app under Accessibility tab in the Security preferences, it does not appear under the Automation tab.

**Comment by milgra** [comment]
Sorry about that, with all the new security stuff Apple added to MacOS lately running an event tap based app became very fragile, try delete the app, remove every mention of the app from the security settings and accessibility settings, then reinstall it, and if it still not working god knows what's the real reason or what other custom event tap based apps are blocking it :(

**Comment by milgra** [comment]
Cannot resolve :(

**Comment by egorvinogradov** [comment]
@milgra Does this mean that the app officially not working anymore?

**Comment by krunk4ever** [comment]
Couldn't get it working either, even with the latest version 3.1. Kept getting the `Not responding` error. Ended trying an alternative [beardedspice](https://github.com/beardedspice/beardedspice) which worked for me.

**Comment by tiziano149** [comment]
Also not working for me on version 3.1, macOS 12.2.1.
