### ISSUE TITLE
App Not Responsive: Bug indentified

### ISSUE THREAD

**Issue by MentalGear** [milgra/macmediakeyforwarder#86]
First off, thanks for this amazing app ! Unfortuanelty, after I just updated to 10.14.6, MacMediaKeyForwwarder just got stuck "not responding" - even after restartting and cleaning all app files related and reenabling the security preferences. This seems to be the same issue that many other reported after an apple update.

After compiling the app from source, the IDE traced the bug to the following line in code:

In applicationDidFinishLaunching:
<img width="968" alt="Screenshot 2019-08-21 at 12 22 51" src="https://user-images.githubusercontent.com/2837147/63424960-c9c20500-c40f-11e9-8c1f-5d3820ee8c3d.png">

Hope this helps, unfortuanetly I don't have enough knowledge in CGTaps or Coca to fix this myself.

**Comment by milgra** [comment]
Hi, thanks for the report, it is a known issue, I couldn't figure out yet why sometimes macos refuses event tapping.

**Comment by Dragao75** [comment]
Is this the same on Catalina (10.15.2)?. The Program usually starts normal. But this morning the app just is Not Responding.

**Comment by TheBogueRat** [comment]
This has been crashing on Catalina since I bought my MacPro 16.  I removed all references to Spotify and compiled.   I don't use Spotify.  No longer crashing on 10.15.2 after a couple days.  Then again, I didn't try compiling from source without removing anything...

**Comment by half-baked1** [comment]
I am also having this issue. Sometimes the app works normally, and sometimes it is completely unresponsive.

**Comment by milgra** [comment]
Cool, thank you, I've added you to the top of the readme!
